require 'albacore'
require 'fileutils'

base_path = File.dirname(__FILE__)
bin_path = "#{base_path}/bin/"
publish_path = "#{base_path}/publish/"
artifacts_path = "#{base_path}/artifacts/"
install_path = ENV["INSTALL_PATH"] || "C:/inetpub/wwwroot"

# // Funcs ///////////////////////////////////

msbuild :msbuild do |msb|
 msb.solution = "AikidoWebsite.sln"
 msb.properties(
	:configuration => :release,
	:outdir => bin_path,
	:webprojectoutputdir => publish_path,
 )
 msb.verbosity = "normal"
 msb.targets = :clean, :build
end

zip :zipartifact do |zip|
	zip.directories_to_zip publish_path
	zip.output_file = "AikidoWebsite.zip"
	zip.output_path = artifacts_path
end

unzip :installZip do |unzip|
	unzip.destination = install_path
	unzip.file = "#{artifacts_path}/AikidoWebsite.zip"
end

# // Tasks //////////////////////////////////

task :default => [ :banner, :build ]

desc "Show Banner"
task :banner do
	puts ""
	puts " 888888                            8   8  8                                "               
	puts " 8    8 e  e   e  e  eeeee eeeee   8   8  8 eeee eeeee  eeeee e eeeee eeee "
	puts " 8eeee8 8  8   8  8  8   8 8  88   88  8  8 8    8   8  8     8   8   8    "
	puts " 88   8 8e 8eee8e 8e 8e  8 8   8   88  8  8 8eee 8eee8e 8eeee 8e  8e  8eee "
	puts " 88   8 88 88   8 88 88  8 8   8   88  8  8 88   88   8    88 88  88  88   "
	puts " 88   8 88 88   8 88 88ee8 8eee8   88ee8ee8 88ee 88eee8 8ee88 88  88  88ee "
	puts "___________________________________________________________________________"
end

desc "Build Website"
task :build => [ :clean, :less, :msbuild, :artifacts ]

desc "Clean Files"
task :clean do
	FileUtils.rm_rf(bin_path, secure: true)
	FileUtils.rm_rf(publish_path, secure: true)
	FileUtils.rm_rf(artifacts_path, secure: true)
end

task :artifacts do
 if (!File.directory?(artifacts_path)) 
	FileUtils.mkdir artifacts_path
 end
 
 Rake::Task[:zipartifact].invoke
 
 puts "##teamcity[publishArtifacts '#{artifacts_path}/AikidoWebsite.zip']"
end

task :install do
	FileUtils.rm_rf("#{install_path}/*", secure: true)
	
	Rake::Task[:installZip].invoke
end

task :less do
	sh %{generateCss.cmd}
end